INSERT INTO BoulderDash.Map (id, mapModel, mapWidth, mapHeight)
VALUES (3,
"U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U
U,S,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,U
U,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,R,R,M,R,M,M,M,M,R,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,D,D,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,R,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,D,M,R,M,M,U
U,M,M,M,M,M,M,M,M,R,M,M,D,M,M,M,M,M,R,M,R,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,B,B,B,B,M,M,M,R,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,R,M,M,M,M,U
U,M,M,M,M,M,M,R,R,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,D,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,M,R,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,M,M,M,M,M,M,M,M,M,R,M,M,M,R,M,M,U
U,M,M,D,M,M,R,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,R,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,R,M,M,M,R,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,R,M,M,M,M,M,B,B,B,B,M,M,M,M,M,D,M,M,M,M,D,M,M,M,M,M,M,R,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,R,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,R,R,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,R,M,M,M,M,M,R,M,M,M,M,M,D,M,R,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,R,M,M,M,D,M,M,M,R,M,D,M,M,R,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,R,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,R,M,M,M,B,B,B,B,M,M,M,M,M,M,M,D,M,M,R,M,M,U
U,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,D,M,M,M,M,R,M,M,U
U,M,M,M,R,M,M,M,M,M,M,M,M,R,M,B,B,B,B,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,D,D,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,M,B,B,B,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,R,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,D,M,M,B,B,B,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,U
U,M,M,M,D,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,R,M,M,M,M,M,M,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,R,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,R,M,M,M,R,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,D,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,R,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,D,M,M,M,U
U,M,M,M,M,M,M,M,M,D,M,R,M,M,R,R,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,R,M,M,M,M,M,M,M,M,R,M,M,M,D,M,M,M,M,D,M,M,M,M,R,M,M,M,M,M,M,U
U,M,M,M,D,M,M,M,M,D,M,M,M,M,M,R,M,M,M,D,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,D,M,M,R,M,M,M,M,M,M,M,M,D,M,M,M,M,M,R,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,R,M,R,R,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,R,R,M,M,M,M,M,M,M,M,M,M,B,B,B,M,R,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,R,M,M,B,B,B,M,M,R,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,R,R,M,M,M,M,B,B,M,M,M,M,M,M,M,M,M,R,M,M,M,D,M,M,M,M,M,M,B,B,B,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,B,B,M,M,M,M,M,M,M,M,M,R,R,M,M,D,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,U
U,B,B,B,B,B,B,B,B,B,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,B,B,B,B,B,B,B,B,B,B,B,B,B,M,M,M,M,M,M,B,B,B,B,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,U
U,M,M,M,M,M,R,M,R,M,R,R,M,R,R,M,D,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,D,D,R,M,M,U
U,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,U
U,M,M,M,M,R,M,M,D,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,R,R,M,M,M,R,M,M,M,M,M,M,M,M,R,M,M,R,M,M,M,D,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,R,M,M,M,U
U,M,M,M,D,D,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,D,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,R,M,M,M,M,U
U,M,M,M,D,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,B,B,R,M,M,M,M,M,D,M,M,M,M,M,R,M,M,M,U
U,M,M,D,M,M,R,M,M,M,M,M,D,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,B,B,M,M,R,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,R,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,B,B,B,B,B,B,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,B,B,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,R,M,M,M,M,M,U
U,M,M,B,B,B,B,B,B,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,D,M,M,M,M,M,D,D,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,R,M,M,U
U,M,M,M,M,M,M,M,M,M,M,D,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,R,M,M,U
U,M,M,D,M,M,R,R,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,U
U,M,M,M,M,R,M,M,M,R,R,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,D,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,R,M,M,R,M,M,M,M,M,M,D,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,D,M,M,M,M,M,D,D,M,M,M,R,R,M,D,M,M,M,M,R,M,M,M,U
U,R,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,M,M,M,D,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,R,M,M,M,R,M,M,M,M,M,U
U,M,M,M,M,M,M,M,D,M,M,M,M,D,M,M,M,M,D,R,M,M,M,M,D,M,M,M,R,M,M,B,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,R,R,M,M,M,M,M,M,M,M,M,U
U,M,M,M,D,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,B,B,B,M,M,M,M,M,M,M,M,M,R,M,M,M,U
U,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,B,B,B,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,M,M,D,R,M,M,M,M,M,R,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,D,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,D,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,U
U,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,U
U,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,R,M,M,M,M,M,M,M,M,M,M,M,M,M,M,M,U
U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U,U"
,64,64)